# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
commands:
  print_pipeline_id:
    Description:  "prints the Circle CI Workflow ID from its environment variable named $CIRCLE_WORKFLOW_ID to the console"
    parameters:
      To:
        type: string
        deafault: $CIRCLE_WORKFLOW_ID
    steps:
      - run: echo << parameters.to >>

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  # print-hello:
  #   # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
  #   docker:
  #     - image: circleci/node:13.8.0
  #   # Add steps to the job
  #   # See: https://circleci.com/docs/2.0/configuration-reference/#steps
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say hello"
  #         command: "echo Hello"
  # print-world:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say world"
  #         command: "echo World"
  # print-author:
  #   docker:
  #     - image: circleci/node:13.8.0
  #   steps:
  #     - checkout
  #     - run:
  #         name: "Say Author Name"
  #         command: echo ${author_name

    write-value:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - run:
            name: "save_hello_world_output"
            command: echo "Testing output" >  ~/output.txt
        - persist_to_workspace:
              root: ~/
              paths:
                - output.txt
  
    print-value:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - attach_workspace:
            at: ~/
        - run:
            name: "print_output_file"
            command: cat  ~/output.txt

    print-pipeline-id:
      docker:
        - image: circleci/node:13.8.0
      steps:
        - checkout
        - print_pipeline_id
      
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - write-value
      - print-value:
          requires: [write-value]
      - print-pipeline-id